import "./global.css";
import "react-toastify/dist/ReactToastify.css";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

import Header from "@/components/header";
import Sidebar from "@/components/sidebar";
import Footer from "@/components/footer";

import Modal from "@/containers/modal";

import ToastContainer from "@/containers/toaster";
import StoreProvider from "@/store/store-provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en" suppressHydrationWarning={true} className={`${inter.className} `}>
      <body>
        <StoreProvider>
          <Modal />
          <div className="flex flex-auto min-w-0 ">
            <div className="sticky top-0 hidden h-screen sm:block">
              <Sidebar />
            </div>

            <main className="relative flex flex-col flex-auto w-full h-full min-w-0 min-h-screen bg-white border-l border-gray-200 dark:bg-gray-800 dark:border-gray-700 ">
              <div className="sticky top-0 border-b border-gray-200 z-40 bg-white h-[64px]">
                <Header />
              </div>
              <div className="flex flex-col flex-auto gap-4 px-8 py-4">


                {children}
              </div>
              <div className="h-[64px] border">
                <Footer />
              </div>
            </main>
          </div>

          <ToastContainer />
        </StoreProvider>
      </body>
    </html>
  );
}
