import "./global.css";
import "react-toastify/dist/ReactToastify.css";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

import Header from "@/components/header";
import Sidebar from "@/components/sidebar";
import Footer from "@/components/footer";

import Modal from "@/containers/modal";

import ToastContainer from "@/containers/toaster";
import StoreProvider from "@/store/store-provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en" suppressHydrationWarning={true} className={`${inter.className} `}>
      <body>
        <StoreProvider>
          <Modal />
          <div className="flex flex-auto min-w-0 ">
            <div className="sticky top-0 hidden h-screen sm:block">
              <Sidebar />
            </div>

            <main className="relative flex flex-col flex-auto w-full h-full min-w-0 min-h-screen bg-white border-l border-gray-200 dark:bg-gray-800 dark:border-gray-700 ">
              <div className="sticky top-0 border-b border-gray-200 z-40 bg-white h-[64px]">
                <Header />
              </div>
              <div className="flex flex-col flex-auto gap-4 px-8 py-4">
                <div className="items-center justify-between gap-3 mb-4 lg:flex">
                  <div className="mb-4 lg:mb-0">
                    <h3 className="text-3xl font-semibold">Dashboard</h3>
                    <p className="text-[#6b7280] text-base">Mevcut portfolio özeti</p>
                  </div>
                  <div className="flex flex-col gap-3 lg:flex-row lg:items-center">
                    <button className="px-3 py-2 text-sm text-gray-600 bg-white border border-gray-300 button dark:bg-gray-700 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600 active:bg-gray-100 dark:active:bg-gray-500 dark:active:border-gray-500 dark:text-gray-100 radius-round h-9">
                      <span className="flex items-center justify-center">
                        <span className="text-lg">
                          <svg
                            stroke="currentColor"
                            fill="none"
                            strokeWidth="0"
                            viewBox="0 0 24 24"
                            height="1em"
                            width="1em"
                            xmlns="http://www.w3.org/2000/svg"
                          >
                            <path
                              strokeLinecap="round"
                              strokeLinejoin="round"
                              strokeWidth="2"
                              d="M3 4a1 1 0 011-1h16a1 1 0 011 1v2.586a1 1 0 01-.293.707l-6.414 6.414a1 1 0 00-.293.707V17l-4 4v-6.586a1 1 0 00-.293-.707L3.293 7.293A1 1 0 013 6.586V4z"
                            ></path>
                          </svg>
                        </span>
                        <span className="ltr:ml-1 rtl:mr-1">Filter</span>
                      </span>
                    </button>
                  </div>
                </div>

                {children}
              </div>
              <div className="h-[64px] border">
                <Footer />
              </div>
            </main>
          </div>

          <ToastContainer />
        </StoreProvider>
      </body>
    </html>
  );
}
